import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const FONTI = path.resolve(import.meta.dirname, '../../fonti/Check e Prog')

// PDF minimo valido con una riga di testo, per simulare la scheda di un altro coach
function pdfConTesto(testo: string) {
  const stream = `BT /F1 12 Tf 60 700 Td (${testo}) Tj ET`
  const obj = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']
  let out = '%PDF-1.4\n'
  const off: number[] = []
  obj.forEach((o, i) => { off.push(out.length); out += `${i + 1} 0 obj\n${o}\nendobj\n` })
  const xref = out.length
  out += `xref\n0 ${obj.length + 1}\n0000000000 65535 f \n${off.map(o => String(o).padStart(10, '0') + ' 00000 n \n').join('')}trailer\n<< /Size ${obj.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`
  return Buffer.from(out)
}

test('note, nome e mezze rep persistono; rimanda chiede conferma; resoconto conserva dati', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Sono Salvatore · usa il mio programma' }).click()
  await page.getByRole('button', { name: /^Inizia/ }).click()
  const rimanda = page.getByRole('button', { name: /occupato, rimanda/ }).first()
  page.once('dialog', d => d.dismiss())
  await rimanda.click()
  await expect(page.getByText('In attesa — attrezzo occupato')).toHaveCount(0)
  page.once('dialog', d => d.accept())
  await rimanda.click()
  await expect(page.getByText('In attesa — attrezzo occupato')).toHaveCount(1)
  await page.getByRole('button').filter({ hasText: 'Mai loggato — si parte oggi' }).first().click()
  await page.getByRole('button', { name: '✎ Personalizza nome' }).click()
  await page.getByLabel('Nome personalizzato').fill('Macchina Hammer personale')
  await page.getByRole('button', { name: 'Salva nome', exact: true }).click()
  await page.getByLabel('Le tue note · per la prossima volta').fill('Sedile 3\nControllare la discesa')
  await page.getByRole('button', { name: 'Chiudi', exact: true }).click()
  await page.reload()
  await expect(page.getByText('Sedile 3\nControllare la discesa')).toBeVisible()
  await page.locator('.card--knurled > button:first-child').filter({ hasText: 'Macchina Hammer personale' }).click()
  await page.locator('.sheet .stepper').nth(1).getByLabel('scrivi il valore').click()
  await page.locator('.sheet .stepper').nth(1).locator('input').fill('7,5')
  await page.locator('.sheet .stepper').nth(1).locator('input').press('Enter')
  await page.getByRole('button', { name: /^Segna / }).click()
  await page.getByRole('button', { name: 'Chiudi', exact: true }).click()
  await page.getByRole('button', { name: /^Chiudi sessione/ }).click()
  await page.getByRole('button', { name: 'A referto' }).click()
  await page.getByRole('button', { name: 'Storico', exact: true }).click()
  await page.getByRole('button').filter({ hasText: 'kg di volume' }).click()
  await expect(page.getByRole('heading', { name: 'Macchina Hammer personale' })).toBeVisible()
  await expect(page.getByRole('cell').filter({ hasText: /kg × 7,5/ })).toBeVisible()
  await expect(page.getByText('Note della seduta')).toBeVisible()
  await page.getByLabel('Cosa ricordare per la prossima seduta').fill('Ripartire dallo stesso carico')
  await page.reload()
  await page.getByRole('button', { name: 'Storico', exact: true }).click()
  await page.getByRole('button').filter({ hasText: 'kg di volume' }).click()
  await expect(page.getByLabel('Cosa ricordare per la prossima seduta')).toHaveValue('Ripartire dallo stesso carico')
  await page.screenshot({ path: 'test-results/workout-mobile.png', fullPage: true })
})

test('import PDF di Antonio: scheda, pasti e check letti sul telefono per un ospite', async ({ page }) => {
  test.skip(!fs.existsSync(FONTI), 'PDF originali non presenti')
  await page.goto('/')
  await page.getByRole('button', { name: 'Inizia con i miei dati', exact: true }).click()
  await page.getByRole('button', { name: 'Sala', exact: true }).click()
  await page.getByRole('button', { name: 'Importa PDF', exact: true }).click()
  await page.getByLabel('Documento PDF').setInputFiles(path.join(FONTI, 'Allenamento - Salvatore Simeoni - Settembre Ottobre.pdf'))
  await page.getByRole('button', { name: 'Leggi PDF', exact: true }).click()
  await expect(page.getByText('5 giorni di allenamento')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Salva e attiva', exact: true })).toBeDisabled()
  await page.screenshot({ path: 'test-results/import-mobile.png', fullPage: true })
  await page.getByRole('checkbox', { name: 'Ho confrontato' }).check()
  await page.getByRole('button', { name: 'Salva e attiva', exact: true }).click()
  await page.getByRole('button', { name: 'Oggi', exact: true }).click()
  await expect(page.getByText(/Settimana .*Settembre Ottobre/)).toBeVisible()
  await expect(page.getByText('Pec fly').first()).toBeVisible()
  await page.getByRole('button', { name: 'Sala', exact: true }).click()
  await page.getByRole('button', { name: 'Importa PDF', exact: true }).click()
  await page.getByLabel('Documento PDF').setInputFiles(path.join(FONTI, 'Alimentazione Salvatore Simeoni Settembre Ottobre.pdf'))
  await page.getByRole('button', { name: 'Leggi PDF', exact: true }).click()
  await expect(page.getByText('4 pasti · 1 check')).toBeVisible()
  await page.getByRole('checkbox', { name: 'Ho confrontato' }).check()
  await page.getByRole('button', { name: 'Salva e attiva', exact: true }).click()
  await page.getByRole('button', { name: 'Tavola', exact: true }).click()
  await expect(page.getByText(/Settembre Ottobre · 0\/4 pasti scelti/)).toBeVisible()
  await page.getByRole('button', { name: 'Check', exact: true }).click()
  await expect(page.getByRole('table')).toContainText('82')
})

test('un PDF di un altro coach non si legge: si archivia e si compila a mano', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Inizia con i miei dati', exact: true }).click()
  await page.getByRole('button', { name: 'Sala', exact: true }).click()
  await page.getByRole('button', { name: 'Importa PDF', exact: true }).click()
  await page.getByLabel('Documento PDF').setInputFiles({ name: 'Scheda Mario.pdf', mimeType: 'application/pdf', buffer: pdfConTesto('GIORNO 1 PETTO - Coach Mario Rossi') })
  await page.getByRole('button', { name: 'Leggi PDF', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('solo per le schede di Antonio Pappa')
  await page.getByRole('button', { name: 'Compila il piano alimentare a mano' }).click()
  await expect(page.getByText('Alimentazione · Il mio piano')).toBeVisible()
  await page.getByRole('checkbox', { name: 'Ho confrontato' }).check()
  await page.getByRole('button', { name: 'Salva e attiva', exact: true }).click()
  await page.getByRole('button', { name: 'Tavola', exact: true }).click()
  await expect(page.getByText(/Il mio piano/)).toBeVisible()
})

test('ospite archivia più PDF offline, evita duplicati, riapre e ripristina gli originali dal backup', async ({ page, browser }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Inizia con i miei dati', exact: true }).click()
  await page.getByRole('button', { name: 'Sala', exact: true }).click()
  await page.getByRole('button', { name: 'Importa PDF', exact: true }).click()
  const pdf = { name: 'Allenamento gennaio.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 gennaio') }
  await page.getByLabel('Documento PDF').setInputFiles(pdf)
  await expect(page.getByRole('button', { name: 'Leggi PDF', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Leggi PDF', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('non si apre come PDF')
  await page.getByRole('button', { name: 'Conserva nell’archivio' }).click()
  await expect(page.getByRole('heading', { name: 'Archivio programmazioni' })).toBeVisible()
  const altri = [pdf, { name: 'Alimentazione gennaio.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 alimentazione gennaio') }, { name: 'Non PDF.pdf', mimeType: 'application/pdf', buffer: Buffer.from('non valido') }]
  await page.getByLabel('PDF da archiviare').setInputFiles(altri)
  await expect(page.getByRole('status')).toContainText('1 PDF aggiunti')
  await expect(page.getByRole('status')).toContainText('1 già presenti')
  await expect(page.getByRole('status')).toContainText('non è un PDF valido')
  await page.getByRole('button').filter({ hasText: 'Allenamento gennaio' }).click()
  await page.getByLabel('Tipo di documento').selectOption('allenamento')
  await page.getByLabel('Data del documento').fill('2025-01-01')
  await expect(page.getByRole('link', { name: 'Apri PDF originale' })).toHaveAttribute('href', /^blob:/)
  const pdfDownload = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Scarica', exact: true }).click()
  expect((await pdfDownload).suggestedFilename()).toBe(pdf.name)
  await page.getByRole('button', { name: 'Chiudi', exact: true }).click()
  await page.getByRole('button', { name: '‹ Torna alla Sala' }).click()
  const backupDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Esporta', exact: true }).click()
  const backup = await backupDownload
  const backupPath = (await backup.path())!
  const nuovo = await browser.newContext()
  const p = await nuovo.newPage()
  await p.goto('/')
  await p.getByRole('button', { name: 'Inizia con i miei dati', exact: true }).click()
  await p.getByRole('button', { name: 'Sala', exact: true }).click()
  p.once('dialog', d => d.accept())
  await p.locator('input[type=file][accept="application/json"]').setInputFiles(backupPath)
  await p.getByRole('button', { name: 'Storico', exact: true }).click()
  await p.getByRole('button', { name: 'Programmazioni', exact: true }).click()
  await p.getByRole('button').filter({ hasText: 'Allenamento gennaio' }).click()
  await expect(p.getByRole('link', { name: 'Apri PDF originale' })).toHaveAttribute('href', /^blob:/)
  await expect(p.getByLabel('Data del documento')).toHaveValue('2025-01-01')
  await nuovo.close()
  await page.reload()
  await expect(page.getByText('Nessuna scheda attiva')).toBeVisible()
  await page.getByRole('button', { name: 'Storico', exact: true }).click()
  await page.getByRole('button', { name: 'Programmazioni', exact: true }).click()
  await expect(page.getByRole('button').filter({ hasText: 'Allenamento gennaio' })).toHaveCount(1)
  await expect(page.getByRole('button').filter({ hasText: 'Alimentazione gennaio' })).toHaveCount(1)
  await page.screenshot({ path: 'test-results/archivio-mobile.png', fullPage: true })
})

test('lettura di un documento archiviato salva lo storico senza attivarlo', async ({ page }) => {
  test.skip(!fs.existsSync(FONTI), 'PDF originali non presenti')
  await page.goto('/')
  await page.getByRole('button', { name: 'Inizia con i miei dati', exact: true }).click()
  await page.getByRole('button', { name: 'Storico', exact: true }).click()
  await page.getByRole('button', { name: 'Programmazioni', exact: true }).click()
  await page.getByLabel('PDF da archiviare').setInputFiles(path.join(FONTI, 'Alimentazione Salvatore Simeoni Aprile.pdf'))
  await page.getByRole('button').filter({ hasText: 'Alimentazione Salvatore Simeoni Aprile' }).click()
  await page.getByRole('button', { name: 'Leggi i dati del PDF' }).click()
  await page.getByRole('button', { name: 'Leggi PDF', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Solo archivio' })).toBeChecked()
  await page.getByRole('checkbox', { name: 'Ho confrontato' }).check()
  await page.getByRole('button', { name: 'Salva nello storico', exact: true }).click()
  await page.getByRole('button').filter({ hasText: 'Aprile' }).first().click()
  await expect(page.getByText('Colazione · 4 opzioni', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Chiudi', exact: true }).click()
  await page.getByRole('button', { name: 'Oggi', exact: true }).click()
  await expect(page.getByText('Nessuna scheda attiva')).toBeVisible()
  await page.getByRole('button', { name: 'Storico', exact: true }).click()
  await expect(page.getByText('I tuoi resoconti compariranno qui dopo il primo allenamento.')).toBeVisible()
})

test('nome per giorno, superserie, timer che sopravvive alla ricarica, eliminazione dallo storico', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Sono Salvatore · usa il mio programma' }).click()
  // la chest press c'è nel giorno 1 e nel giorno 5: la rinomino solo nel 5
  await page.getByRole('button', { name: /^G5 ·/ }).click()
  await page.getByRole('button').filter({ hasText: /^Chest press/ }).click()
  await page.getByRole('button', { name: '✎ Personalizza nome' }).click()
  await page.getByLabel('Nome personalizzato').fill('Chest press Flex Leverage')
  await page.getByRole('button', { name: 'Salva nome', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Chest press Flex Leverage' })).toBeVisible()
  await page.getByRole('button', { name: 'Chiudi', exact: true }).click()
  await page.getByRole('button', { name: /^G1 ·/ }).click()
  await expect(page.getByText('Chest press Flex Leverage')).toHaveCount(0)
  await expect(page.getByText('Chest press', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^G5 ·/ }).click()

  // superserie: alzate laterali + chest press, il recupero parte solo a fine giro
  await page.getByRole('button').filter({ hasText: /^Alzate laterali manubri/ }).click()
  await page.getByRole('button', { name: '⇄ Fai in superserie con Chest press Flex Leverage' }).click()
  await page.getByRole('button', { name: /^Segna / }).click()
  await expect(page.getByRole('heading', { name: 'Chest press Flex Leverage' })).toBeVisible()
  await expect(page.getByRole('timer')).toHaveCount(0)
  await page.getByRole('button', { name: /^Segna / }).click()
  await expect(page.getByRole('heading', { name: 'Alzate laterali manubri' })).toBeVisible()
  await expect(page.getByRole('timer')).toContainText('quando ti senti pronto')
  await page.getByRole('button', { name: 'Chiudi', exact: true }).click()
  await page.screenshot({ path: 'test-results/superserie-mobile.png', fullPage: true })

  // l'app si ricarica (come quando iOS la chiude in background): il timer c'è ancora
  await page.reload()
  await expect(page.getByRole('timer')).toBeVisible()
  await page.getByRole('button', { name: /^Chiudi sessione/ }).click()
  await page.getByRole('button', { name: 'A referto' }).click()
  await expect(page.getByRole('timer')).toHaveCount(0)

  await page.getByRole('button', { name: 'Storico', exact: true }).click()
  await page.getByRole('button').filter({ hasText: 'kg di volume' }).click()
  await expect(page.getByRole('heading', { name: 'Chest press Flex Leverage' })).toBeVisible()
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Elimina questo allenamento' }).click()
  await expect(page.getByText('I tuoi resoconti compariranno qui dopo il primo allenamento.')).toBeVisible()
})
